### ISSUE TITLE
Add method which checks how a request has been made with a schema

### ISSUE THREAD

**Issue by rickschubert** [trayio/mock-inspect#40]
Currently, there is a method `expectRequestMadeMatching` which performs an exact match comparison to check whether the network request has been made with the supplied parameters.

I would find it useful to have another method called `expectRequestMadeMatchingSchema`. This method would work the same way as `expectRequestMadeMatching` but users would be able to pass in JSON schemas which are then being validated. 

This new feature would help in cases where parameters are being auto-generated by the application code, i.e. when it always passes a parameter `id` which is then a random uuid.

**Comment by thomaschaplin** [comment]
@rickschubert would you be able to provide a pseudo-code example of the suggested enhancement? Not the implementation but just an example test of how it _could_ be used/invoked.

**Comment by rickschubert** [comment]
@thomaschaplin This is a pseudo-code exmaple on how I imagine the invocation. What this uses here is JSON schema - this is the same format which gets generated (and checked against) using jest-json-schema and jest-json-schema-extended. This format is also the basis for PACT contract tests. Therefore, mock-inspect could even build some sort of "bridge" to other contract testing frameworks. So let's say people already have contracts, but they don't use our example based contract format but instead JSON schema PACT contracts, then they could still pass them in.

```js
const req = mockRequest({
    requestPattern: "/login",
    requestMethod: "POST",
    responseBody: {message: "Hello"}
})
// Execute code which makes the request to /login
req.expectRequestMadeMatchingSchema({
    "type": "object",
    "properties": {
        "results": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "replySchema": {
                        "anyOf": [
                            {
                                "type": "null"
                            },
                            {
                                "type": "object"
                            }
                        ]
                    },
                    "delivery": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "additionalProperties": true,
                "required": [
                    "id",
                    "replySchema",
                    "delivery"
                ]
            },
            "minItems": 1
        },
        "total": {
            "type": "number"
        }
    },
    "additionalProperties": true,
    "required": [
        "results",
        "total"
    ]
})
```

The same example but using `jest-json-schema-extended` as schema builder:

```js
const req = mockRequest({
    requestPattern: "/login",
    requestMethod: "POST",
    responseBody: {message: "Hello"}
})
// Execute code which makes the request to /login
req.expectRequestMadeMatchingSchema(
    objectWithRequiredProps({
        total: numberType,
        results: arrayOfItems(objectWithRequiredProps({
            id: numberType,
            replySchema: anyOf([nullType, objectType])
        }))
    })
)
```

**Comment by rickschubert** [comment]
I have implemented this feature now and it works, you can find it on this branch: `rick-schubert/qa-2286/implement-schema-match-function-into-mock-inspect`

But I am suddenly thinking: Perhaps we shouldn't do this. There would be a better way to deal with these problems. We could instead create simply a method which returns to the user all of the information about the request. I could imagine this like below:

```ts
const req = mockRequest({/*properties here ...*/})
const requestInfo = req.getInfoHowRequestWasMade()
```

The funtion I outlined above could return an object with properties such as the request headers which have been used as well as the request payload. That way, we wouldn't have to place such a function into mock-inspect at all and the user could simply build something like it themselves.

I think that this would be better because it would be easier to understand for users and it also means we wouldn't have to be accountable for updates, i.e. when a dependency needs to be updates. I think it would also make it easier for people to understand how to work with mock-inspect as many people I believe rather prefer doing simple things like schema checking themselves. And they could use our tool that way however they like.

I think adding the above would be a great idea; but here comes a bit of a radical suggestion: Does this mean we should get rid of `expectRequestMadeMatchingSchema` and `expectRequestMadeMatchingContract`? Experience from tray at least shows that `expectRequestMadeMatchingContract` is never used; and `expectRequestMadeMatchingSchema` is used but could easily be replaced with a jest call instead. (i.e. `expect(req.getInfoHowRequestWasMade().requestPayload).toEqual({here_goes: "the expectation object"})`).

Thoughts @thomaschaplin?

**Comment by rickschubert** [comment]
And you know how we are going to call this method? `inspect()` - so you call `mock.inspect()` 😂 

```ts
const mock = mockRequest({/*mock options go here ...*/})
const requestMadeInfo = mock.inspect() // this returns an object containing
                                       // information about how the request was made
// The user can then use this information however they want:
expect(requestMadeInfo.requestBody).toEqual({propertyA: "Hello world"})
```

![image](https://user-images.githubusercontent.com/25436915/116603331-bb3a2980-a924-11eb-8301-b5b8d0b09dfe.png)

**Comment by thomaschaplin** [comment]
@rickschubert I think you've just hit the nail on the head. I haven't checked out your branch yet. However, I'm up for exploring this new idea of `mock.inspect()`. Let's have an in-depth discussion on this topic over zoom and we can summarise everything in a comment on this issue.

![damn-daniel](https://user-images.githubusercontent.com/35810778/116609844-c3966280-a92c-11eb-8874-ffaa4c7833ff.gif)
